server:
  display-name: xiu-love
  port: 8081
  servlet-path: /xiu
spring:
  profiles:
    active: dev
  application:
    name: xiu-love


management:
  security:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    console: '%d [%thread] [%X{trace_id:--}] %-5level %logger - %msg%n'
  path: /home/logs

endpoints:
  actuator:
    sensitive: false


