server:
  display-name: daydayup
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: daydayup

weather:
  recent:
    key: ce896f3a8bed406eb416f0ae77bbd259
  baidu:
    key: Gy7SGUigZ4HxGYDaq9azWy09

management:
  security:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    console: '%d [%thread] [%X{trace_id:--}] %-5level %logger - %msg%n'
  path: /home/logs

endpoints:
  actuator:
    sensitive: false


